// examples/minimal/src/root.tsx
import { useEntryPoint } from "@biliblitz/blitz";
import { useHead } from "@unhead/vue";
import { defineComponent, h } from "vue";
import { RouterView } from "vue-router";

export default defineComponent({
  setup() {
    useHead({
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width, initial-scale=1.0" },
      ],
    });

    useEntryPoint();

    return () => h(RouterView);
  },
});

// examples/adapter-workers/src/root.tsx
import { BlitzCityProvider, RouterHead, RouterOutlet } from "@biliblitz/blitz";

/**
 * Main entry of the whole application.
 */
export default function Root() {
  return (
    <BlitzCityProvider lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <RouterHead />
      </head>
      <body>
        <RouterOutlet />
      </body>
    </BlitzCityProvider>
  );
}
