// examples/adapter-static/src/root.tsx
import { BlitzCityProvider, RouterHead, RouterOutlet } from "@biliblitz/blitz";

import "./assets/style.css";

/**
 * Main entry of the whole application.
 */
export default function Root() {
  return (
    <BlitzCityProvider lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <RouterHead />
      </head>
      <body>
        <RouterOutlet />
      </body>
    </BlitzCityProvider>
  );
}

// examples/adapter-static/src/root.vue
<script setup>
import { useEntryPoint } from "@biliblitz/blitz";
import { useHead } from "@unhead/vue";

import "./assets/style.css";

useHead({
  meta: [
    { charset: "utf-8" },
    { name: "viewport", content: "width=device-width, initial-scale=1.0" },
  ],
});

useEntryPoint();
</script>

<template>
  <router-view />
</template>
